# Generated by Django 4.2.4 on 2023-08-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='posts',
            field=models.ManyToManyField(through='posts.HomepageSectionOrder', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='homepagesectionorder',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepagesectionorder_set', to='posts.post'),
        ),
    ]
