# Generated by Django 4.2.4 on 2023-08-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auto_generate_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
