# Generated by Django 4.2.4 on 2023-08-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesectionorder',
            name='post',
        ),
        migrations.RemoveField(
            model_name='homepagesectionorder',
            name='section',
        ),
        migrations.DeleteModel(
            name='HomepageSection',
        ),
        migrations.DeleteModel(
            name='HomepageSectionOrder',
        ),
    ]
